# permissions for end users to edit croncrawlerjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: croncrawlerjob-editor-role
rules:
- apiGroups:
  - cronjob.crawler.com
  resources:
  - croncrawlerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronjob.crawler.com
  resources:
  - croncrawlerjobs/status
  verbs:
  - get
