# permissions for end users to view croncrawlerjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: croncrawlerjob-viewer-role
rules:
- apiGroups:
  - cronjob.crawler.com
  resources:
  - croncrawlerjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cronjob.crawler.com
  resources:
  - croncrawlerjobs/status
  verbs:
  - get
